### ISSUE TITLE
chatbot is not working🥺😭😭😭😭

### ISSUE THREAD

**Issue by kpiyush04** [rahulchauhan049/birthday-gift-website#1]
please provide chatbot page as soon as possible we are eagerly waiting for it😌😌😌😌

**Comment by rahulchauhan049** [comment]
@kpiyush04 Chatbot is sending API requests to dialogflow, so it needs a live server in order to work. Try running the webpage using a live server. You can also create your custom replies for the chatbot, just make a chatbot using dialogflow and replace the API link with your own dialogflow API link
